#!/bin/bash
cd "$(dirname "$0")"
stow -vv */

# Reload shell configuration
if [ $(basename $SHELL) = "fish" ]; then
    echo "Execute 'source ~/.config/fish/fish_config' to reload fish configuration."
else
    echo "Execute 'source ~/.bashrc' to reload bash configuration."
fi
