#!/bin/fish
# vim: set ft=fish:

set BASEDIR (dirname (status -f))

# bin
mkdir -pv ~/.bin
for file in (dir $BASEDIR/bin);
    echo $BASEDIR/bin$file
    #    ln -sf $BASEDIR/bin/$file ~/.bin/$file
end
