" begin plugins
" ------------------------------------------------------------------------------
" Run our plugin manager
call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-easy-align'
Plug 'bling/vim-airline'
Plug 'edkolev/promptline.vim'
Plug 'tpope/vim-fugitive'

call plug#end()

" Airline plugin
set guifont=Droid\ Sans\ Mono\ for\ Powerline\ 10
let g:airline_powerline_fonts = 1
let g:airline_theme = 'papercolor'

" end plugins
" ------------------------------------------------------------------------------

" be iMproved
set nocompatible

" Turn line numbers on
set nu

" Turn on syntax highlighting
syntax on

" Set color scheme
color miro8

" Make sure the statusline is always on
set laststatus=2

" Default indentation: 4 spaces
set ts=4 sts=4 sw=4 expandtab

" Remap j and k to move up a row instead of a line
" (useful for line wraps)
nnoremap j gj
nnoremap k gk

" Remap <Esc> to jj and kk in insert mode
inoremap jj <Esc>
inoremap kk <Esc>

" Only do this part when compiled with support for autocommands
if has("autocmd")
	" Enable file type detection
	filetype on

	" Syntax of these languages is fussy over tabs vs spaces
	autocmd FileType make setlocal ts=4 sts=4 sw=4 noexpandtab
	autocmd FileType yaml setlocal ts=4 sts=4 sw=4 expandtab

	" Customizations based on house-style (arbitrary)
	autocmd FileType html setlocal ts=4 sts=4 sw=4 expandtab
	autocmd FileType css setlocal ts=4 sts=4 sw=4 expandtab
endif
