#! /bin/sh

# Set our background wallpaper
source ~/.fehbg &

# Start our compositor
compton &

# Make our cursor nice and pretty
xsetroot -cursor_name left_ptr &

# Start a terminal
urxvtd -f -o -q
urxvtc &

# Launch our keybind daemon
sxhkd $HOME/.config/sxhkd/sxhkd.bspwm &

# Panel configuration


# bspwm configuration
bspc config border_width        2
bspc config window_gap         12
#bspc config top_padding $PANEL_HEIGHT

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc monitor -d term web docs comms media

bspc rule -a Chromium desktop=^2 fullscreen=on floating=on
bspc rule -a libreoffice desktop=^3

bspwm desktop web -l monocle
bspwm desktop docs -l monocle

# Panel
#panel &
