#! /bin/sh

# Load our X resources
xrdb -load .Xresources

# Make caps-lock useful
setxkbmap -option caps:escape

# Make our cursor nice and pretty
xsetroot -cursor_name left_ptr &

# Now hide it
#unclutter -idle 1 &

# Set our background wallpaper
source $HOME/.fehbg &

# Start our compositor
compton --xrender-sync --xrender-sync-fence &

# Start a terminal
termite &

# Launch our keybind daemon
sxhkd > /dev/null &

# bspwm configuration
bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

if [ "$HOSTNAME" == equinox ]; then
    bspc monitor eDP1 -d term web docs comms media
    bspc monitor HDMI1 -d media
else
    bspc monitor -d term web docs comms media
fi

bspc rule -a Chromium desktop=^2 fullscreen=on floating=on
bspc rule -a Firefox desktop=^2 fullscreen=on floating=on
bspc rule -a libreoffice desktop=^3 fullscreen=on floating=on
bspc rule -a Zathura state=tiled
