#! /bin/sh

# Launch our keybind daemon
sxhkd > /dev/null &

# bspwm configuration
bspc config border_width          4
bspc config active_border_color   '#4c566a'
bspc config focused_border_color  '#4c566a'
bspc config normal_border_color   '#3b4252'
bspc config window_gap            12
bspc config split_ratio           0.50
bspc config focus_follows_pointer true

bspc monitor -d term web comms games docs

bspc rule -a Chromium desktop=^2 fullscreen=on floating=on
bspc rule -a Firefox desktop=^2 fullscreen=on floating=on
bspc rule -a libreoffice desktop=^5 fullscreen=on
bspc rule -a Zathura state=tiled
bspc rule -a discord desktop=^3
bspc rule -a Gnome-calculator state=floating

# Launch our bar
bar
