#! /bin/sh

# Launch our keybind daemon
sxhkd > /dev/null &

# bspwm configuration
bspc config border_width          4
bspc config active_border_color   '#006b8d'
bspc config focused_border_color  '#006b8d'
bspc config normal_border_color   '#003549'
bspc config window_gap            12
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc monitor -d term web docs comms games

bspc rule -a Chromium desktop=^2 fullscreen=on floating=on
bspc rule -a Firefox desktop=^2 fullscreen=on floating=on
bspc rule -a libreoffice desktop=^3 fullscreen=on
bspc rule -a Zathura state=tiled

# Launch our bar
bar
